trigger:
- main

pool:
  name: 'MyPool'

steps:
- script: echo "Installing dependencies"
- script: echo "Building Application"
- script: echo "Running Tests"
- script: echo "Deploying Application"